package Spring.model.enums.binance.futures.coinm;

public enum Symbol {
    _LINKUSD_231229("LINKUSD_231229"),
    _DOTUSD_230929("DOTUSD_230929"),
    _FILUSD_PERP("FILUSD_PERP"),
    _XRPUSD_231229("XRPUSD_231229"),
    _GMTUSD_PERP("GMTUSD_PERP"),
    _XTZUSD_PERP("XTZUSD_PERP"),
    _BCHUSD_PERP("BCHUSD_PERP"),
    _BCHUSD_230929("BCHUSD_230929"),
    _XRPUSD_230929("XRPUSD_230929"),
    _LINKUSD_PERP("LINKUSD_PERP"),
    _BTCUSD_PERP("BTCUSD_PERP"),
    _XRPUSD_PERP("XRPUSD_PERP"),
    _LINKUSD_230929("LINKUSD_230929"),
    _RUNEUSD_PERP("RUNEUSD_PERP"),
    _BTCUSD_231229("BTCUSD_231229"),
    _CHZUSD_PERP("CHZUSD_PERP"),
    _BNBUSD_230929("BNBUSD_230929"),
    _TRXUSD_PERP("TRXUSD_PERP"),
    _ALGOUSD_PERP("ALGOUSD_PERP"),
    _BNBUSD_231229("BNBUSD_231229"),
    _DOGEUSD_PERP("DOGEUSD_PERP"),
    _AVAXUSD_PERP("AVAXUSD_PERP"),
    _SANDUSD_PERP("SANDUSD_PERP"),
    _MATICUSD_PERP("MATICUSD_PERP"),
    _EOSUSD_PERP("EOSUSD_PERP"),
    _LTCUSD_231229("LTCUSD_231229"),
    _ATOMUSD_PERP("ATOMUSD_PERP"),
    _BTCUSD_230929("BTCUSD_230929"),
    _THETAUSD_PERP("THETAUSD_PERP"),
    _LTCUSD_230929("LTCUSD_230929"),
    _OPUSD_PERP("OPUSD_PERP"),
    _ETCUSD_210924("ETCUSD_210924"),
    _XLMUSD_PERP("XLMUSD_PERP"),
    _ADAUSD_230929("ADAUSD_230929"),
    _ETCUSD_PERP("ETCUSD_PERP"),
    _EOSUSD_210924("EOSUSD_210924"),
    _UNIUSD_PERP("UNIUSD_PERP"),
    _EGLDUSD_PERP("EGLDUSD_PERP"),
    _XMRUSD_PERP("XMRUSD_PERP"),
    _BTCETH_PERP("BTCETH_PERP"),
    _LTCUSD_PERP("LTCUSD_PERP"),
    _MANAUSD_PERP("MANAUSD_PERP"),
    _FTMUSD_PERP("FTMUSD_PERP"),
    _ICXUSD_PERP("ICXUSD_PERP"),
    _DOTUSD_PERP("DOTUSD_PERP"),
    _AAVEUSD_PERP("AAVEUSD_PERP"),
    _ETHUSD_PERP("ETHUSD_PERP"),
    _APEUSD_PERP("APEUSD_PERP"),
    _BCHUSD_231229("BCHUSD_231229"),
    _ETHUSD_231229("ETHUSD_231229"),
    _ADAUSD_PERP("ADAUSD_PERP"),
    _BNBUSD_PERP("BNBUSD_PERP"),
    _SOLUSD_PERP("SOLUSD_PERP"),
    _KNCUSD_PERP("KNCUSD_PERP"),
    _ETHBTC_PERP("ETHBTC_PERP"),
    _ADAUSD_231229("ADAUSD_231229"),
    _ENSUSD_PERP("ENSUSD_PERP"),
    _ETHUSD_230929("ETHUSD_230929"),
    _ROSEUSD_PERP("ROSEUSD_PERP"),
    _APTUSD_PERP("APTUSD_PERP"),
    _AXSUSD_PERP("AXSUSD_PERP"),
    _NEARUSD_PERP("NEARUSD_PERP"),
    _DOTUSD_231229("DOTUSD_231229"),

    ;

    private final String value;

    Symbol(String value) {
        this.value = value;
    }

    public String getValue() {
        return value;
    }


}
